services:
  - type: web
    name: higo-notification-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # أضف serviceAccountKey.json كـ Secret File في Render Dashboard
